apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: codegen-0507
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-0507 
  name: codegen-0507
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: codegen-0507 


# apiVersion: v1
# kind: Service
# metadata:
#   name: llamacpp-svc
#   namespace: test-proj
# spec:
#   ports:
#   - port: 8501
#     protocol: TCP
#     targetPort: 8501
#   selector:
#     app: codegen
#   type: ClusterIP
